<div class="wrapper content-padding">
  <div id="master_list" class="content-page">
    <h2>Red Team Directory</h2>
    <h3>Kate, Nikki, Chris</h3>
    <table width="1000" cellpadding="8" cellspacing="0" style="font-size:14px; font-family:Arial, Helvetica, sans-serif;">
      <tr style="font-weight:bold; height:35px;">
        <td width="60" style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; background-color:#000000; color:#ffffff;"> Code </td>
        <td width="250" style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; background-color:#000000; color:#ffffff;"> Dealership </td>
        <td width="310" style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; background-color:#000000; color:#ffffff;"> Website </td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; background-color:#000000; color:#ffffff;"> CMS </td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; background-color:#000000; color:#ffffff;"> CRM </td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; background-color:#000000; color:#ffffff;"> DOC </td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#ffffff; background-color:#ff0000; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=tUFl3WI5YNUGJxIL0MiDAGQ#gid=64" title="Rick Case Georgia - AE Portal" target="_new" style="color:#ffffff; text-decoration:none;"> RCGA </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=tUFl3WI5YNUGJxIL0MiDAGQ#gid=64" title="Rick Case Georgia - Audi Gwinnett - Main Website - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Audi Gwinnett (Rick Case) </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.audigwinnett.com" title="Rick Case Georgia - Audi Gwinnett - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.audigwinnett.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.audigwinnett.com/admin" title="IZMO Cars Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Izmo Cars </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://my.dealersocket.com/crm/login.aspx" title="Dealer Socket Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer Socket </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/129oMa3IM4Iyb6Zt3IDSKVfWMOqaLL91G4uJVDmWU420/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" border="0"> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#ffffff; background-color:#ff0000; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dFBCOFRSeU56dC1uRzgxSVZ4aXRsaXc#gid=64" title="Audi of Columbia - AE Portal" target="_new" style="color:#ffffff; text-decoration:none;"> AUCO </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid; padding-left:10px;"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dFBCOFRSeU56dC1uRzgxSVZ4aXRsaXc#gid=64" title="Audi of Columbia - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Audi of Columbia </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.audicolumbia.com" title="Audi of Columbia - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.audicolumbia.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"> - - - - </td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1LnRKsrzMe_g5WJkn3bHbiuDeF4p1Q95IdXYS-DcOCgs/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" border="0"> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#ffffff; background-color:#ff0000; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dHBpUUFwUXZxUnU4QTAxNFMya2kxUWc#gid=64" title="BMW of Columbia - AE Portal" target="_new" style="color:#ffffff; text-decoration:none;"> BMCO </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dHBpUUFwUXZxUnU4QTAxNFMya2kxUWc#gid=64" title="BMW of Columbia - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> BMW of Columbia </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.bmwofcolumbia.com" title="BMW of Columbia - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.bmwofcolumbia.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="##" title="##" target="_new" style="color:#000000; text-decoration:none;"> CMS </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="##" title="##" target="_new" style="color:#000000; text-decoration:none;"> - - - - </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/18ETyriYzDu6sdSH1cGDyA8AYFnNhja68dtI1BQ_Zz2Q/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" border="0"> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#ffffff; background-color:#ff0000; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dHhqYXNlbUFvNGRtYzc4bHJlZW9IZ0E#gid=64" title="Boardwalk Acura - AE Portal" target="_new" style="color:#ffffff; text-decoration:none;"> BOAC </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dHhqYXNlbUFvNGRtYzc4bHJlZW9IZ0E#gid=64" title="Boardwalk Acura - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Boardwalk Acura </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.boardwalkacura.com" title="Boardwalk Acura - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.boardwalkacura.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="##" title="##" target="_new" style="color:#000000; text-decoration:none;"> - - - - </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1SFwkDSHEX32Ecexqc_3cl56eG7s8f2H3sMLekKepMOY/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" border="0"> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#ffffff; background-color:#ff0000; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dDVwc2ZpclkzVm43aERfY0c1RklWWnc#gid=64" title="Boardwalk Honda - AE Portal" target="_new" style="color:#ffffff; text-decoration:none;"> BOHO </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dDVwc2ZpclkzVm43aERfY0c1RklWWnc#gid=64" title="Boardwalk Honda - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Boardwalk Honda </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.hondaboardwalk.com" title="Boardwalk Honda - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.hondaboardwalk.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="##" title="##" target="_new" style="color:#000000; text-decoration:none;"> - - - - </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1fnJ2DCQ7sD-fYhCHb0idpuQHN0RW_437sz4Cz2nRZ6g/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" border="0"> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#ffffff; background-color:#ff0000; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=to5hG70DpWB4-qOJVN9x-EA#gid=64" title="Curry Honda Atlanta - AE Portal" target="_new" style="color:#ffffff; text-decoration:none;"> CUHO </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=to5hG70DpWB4-qOJVN9x-EA#gid=64" title="Curry Honda Atlanta - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Curry Honda Atlanta </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.curryhondaga.com" title="Curry Honda Atlanta - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.curryhondaga.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"> Higher Gear </td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1QB3d4NfylJ-BZeUuZJcRcem9qvhLoi-nw63c3ZPA_kQ/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" border="0"> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#ffffff; background-color:#ff0000; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=t-Crhe9Q6tMUQfV4BH7VuaA#gid=64" title="Curry Hyundai - AE Portal" target="_new" style="color:#ffffff; text-decoration:none;"> CUHY </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=t-Crhe9Q6tMUQfV4BH7VuaA#gid=64" title="Curry Hyundai - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Curry Hyundai </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.curryhyundai.com" title="Curry Hyundai - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.curryhyundai.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"> Higher Gear </td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1sKf71_625SbrZ5JZagFMUkuTDQpqhfzA2nEpFSQ-yps/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" border="0"> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#ffffff; background-color:#ff0000; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=tbxXC7RiBXhhI1shyf6eKjg#gid=64" title="Curry Subaru - AE Portal" target="_new" style="color:#ffffff; text-decoration:none;"> CUSU </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=tbxXC7RiBXhhI1shyf6eKjg#gid=64" title="Curry Subaru - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Curry Subaru </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.currysubaru.com" title="Curry Subaru - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.currysubaru.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"> Higher Gear </td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/16uuftcgSYVWix-JXdvy9CY9pwnTdFEFVTex3MVBL3cM/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" border="0"> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#ffffff; background-color:#ff0000; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=0Ag35Ehid_faMdDVfS2E3cW03cGk3TmFhTUhlSWtsT3c&hl=en#gid=64" title="Curry Toyota - AE Portal" target="_new" style="color:#ffffff; text-decoration:none;"> CUTO </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=0Ag35Ehid_faMdDVfS2E3cW03cGk3TmFhTUhlSWtsT3c&hl=en#gid=64" title="Curry Toyota - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Curry Toyota </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.currytoyota.com" title="Curry Toyota - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.currytoyota.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"> Higher Gear </td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1gNb5sY8twd1q6ZISJq65HWitlUGLUsejmkTTEGodf8s/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" border="0"> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#ffffff; background-color:#ff0000; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dFRXU3BQc1RITmh2S0tIRC03Njg2S2c#gid=64" title="Ed Napleton Honda of Oak Lawn - AE Portal" target="_new" style="color:#ffffff; text-decoration:none;"> ENOL </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dFRXU3BQc1RITmh2S0tIRC03Njg2S2c#gid=64" title="Ed Napleton Honda of Oak Lawn - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Ed Napleton Honda of Oak Lawn </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.ednapletonhonda.com" title="Ed Napleton Honda of Oak Lawn - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.ednapletonhonda.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://www.car-research.com/carinteractive/WebXRM/loginpage.aspx" title="Car Research Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Car Research </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1Y2Qd4DlLhuZW8TPPnQw1kSi0f6WGdij4hTQQDXTbPf4/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" border="0"> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#ffffff; background-color:#ff0000; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=txnGbyVnlj4e9KCtjO959Ww#gid=64" title="Friendship Chrysler Jeep Dodge - AE Portal" target="_new" style="color:#ffffff; text-decoration:none;"> FCJD </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=txnGbyVnlj4e9KCtjO959Ww#gid=64" title="Friendship Chrysler Jeep Dodge - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Friendship Chrysler Jeep Dodge </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.friendshipchryslerjeepdodge.com" title="Friendship Chrysler Jeep Dodge - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.friendshipchryslerjeepdodge.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"> ADP </td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1lI7CDD0RYLdo70ePwEqkgO71RXlHx4wo_RtbV0oyBok/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" border="0"> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#ffffff; background-color:#ff0000; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=tqyzZWocRryUQ6C-KYjq5tg#gid=64" title="Friendship Ford - AE Portal" target="_new" style="color:#ffffff; text-decoration:none;"> FRFO </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=tqyzZWocRryUQ6C-KYjq5tg#gid=64" title="Friendship Ford - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Friendship Ford </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.friendshipfordofbristol.com" title="Friendship Ford - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.friendshipfordofbristol.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"> ADP </td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1rEPqgw4Jgz8DUDoPk0SFbqef5MiYedEQs2hShrxNNQ0/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" border="0"> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#ffffff; background-color:#ff0000; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0Ag35Ehid_faMdHF5elpXb2NScnlVUTZDLUtZanE1dGc#gid=64" title="Friendship Hyundai - AE Portal" target="_new" style="color:#ffffff; text-decoration:none;"> FRHY </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0Ag35Ehid_faMdHF5elpXb2NScnlVUTZDLUtZanE1dGc#gid=64" title="Friendship Hyundai - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Friendship Hyundai </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.friendshiphyundaiofbristol.com" title="Friendship Hyundai - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.friendshiphyundaiofbristol.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"> ADP </td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1UzUgsi3zCd9GJg08ryyT3Hi6v5DTMolmPkSwiCJBEnk/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" border="0"> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#ffffff; background-color:#ff0000; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=tqyzZWocRryUQ6C-KYjq5tg#gid=64" title="Friendship Volvo - AE Portal" target="_new" style="color:#ffffff; text-decoration:none;"> FRVO </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=tqyzZWocRryUQ6C-KYjq5tg#gid=64" title="Friendship Volvo - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Friendship Volvo </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.friendshipvolvoofbristol.com" title="Friendship Volvo - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.friendshipvolvoofbristol.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"> ADP </td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1cTBCwhLBSIptIfAEy6teW43XQ8zS2NNmXmCEayVgA6E/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" border="0"> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#ffffff; background-color:#ff0000; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=tu3JiKbWnE3vkUOI94yAorA#gid=64" title="Friendship Honda Of Boone - AE Portal" target="_new" style="color:#ffffff; text-decoration:none;"> FRHO </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=tu3JiKbWnE3vkUOI94yAorA#gid=64" title="Friendship Honda Of Boone - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Friendship Honda Of Boone </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.friendshiphonda.com" title="Friendship Honda Of Boone - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.friendshiphonda.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"> Higher Gear </td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1gYhViuPF9LSVHqBJi9nW4KIHdwR7VLiaYFutuEizixM/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" border="0"> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#ffffff; background-color:#ff0000; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dF9HcGJwTjg0cE5YdjZsbFJvWmpEdnc#gid=64" title="Friendship Hyundai of Johnson City - AE Portal" target="_new" style="color:#ffffff; text-decoration:none;"> FRJC </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dF9HcGJwTjg0cE5YdjZsbFJvWmpEdnc#gid=64" title="Friendship Hyundai of Johnson City - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Friendship Hyundai of Johnson City </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.friendshiphyundaijc.com" title="Friendship Hyundai of Johnson City - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.friendshiphyundaijc.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"> ADP </td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1hARFS0S6XWvJM0yYcSu93SaO4voZA8HauNGThhMb6D4/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" border="0"> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#ffffff; background-color:#ff0000; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dHYtSkJnTFltMTV6T05mUWI0RXpnbXc#gid=64" title="Hilton Head BMW - AE Portal" target="_new" style="color:#ffffff; text-decoration:none;"> HHBM </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dHYtSkJnTFltMTV6T05mUWI0RXpnbXc#gid=64" title="Hilton Head BMW - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Hilton Head BMW </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.hiltonheadbmw.com" title="Hilton Head BMW - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.hiltonheadbmw.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/141fTnQebDljjXEgwJkM7JK7rAIKzQjVr_W_u1NQ7iJk/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" border="0"> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#ffffff; background-color:#ff0000; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dExnZmtlMzVUUERkSmRMUUZVR1JFVHc#gid=64" title="Kendall Toyota - AE Portal" target="_new" style="color:#ffffff; text-decoration:none;"> KETO </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dExnZmtlMzVUUERkSmRMUUZVR1JFVHc#gid=64" title="Kendall Toyota - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Kendall Toyota </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.kendalltoyota.com" title="Kendall Toyota - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.kendalltoyota.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://login.nakedlime.com/Login/Login.aspx?ReturnUrl=%2fDefault.aspx" title="Naked Lime Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Naked Lime </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealercrm.com/" title="iMagic Control Panel" target="_new" style="color:#000000; text-decoration:none;"> iMagic </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/17-t5O0mfrlG5uFXQvSeGDbgXXOafTwfnafqW2AJfOD0/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" border="0"> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#ffffff; background-color:#ff0000; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dHF4OGRsZzI5TEtmY1dhd0d0QWtldHc#gid=64" title="Kings Mazda - AE Portal" target="_new" style="color:#ffffff; text-decoration:none;"> KIMA </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dHF4OGRsZzI5TEtmY1dhd0d0QWtldHc#gid=64" title="Kings Mazda - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Kings Mazda </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.kingsmazda.com" title="Kings Mazda - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.kingsmazda.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"> Send Blaster </td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1fbDVAsUN02VOxdv6pKmyc4hAUcIWHvLWXd_BcsPSaAg/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" border="0"> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#ffffff; background-color:#ff0000; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dF9ZbjlVLVVlWFVxSlJRQjhVdjlQQmc#gid=64" title="McGrath Lexus - AE Portal" target="_new" style="color:#ffffff; text-decoration:none;"> MCLE </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dF9ZbjlVLVVlWFVxSlJRQjhVdjlQQmc#gid=64" title="McGrath Lexus - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> McGrath Lexus </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.mcgrathlexusofchicago.com" title="McGrath Lexus - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.mcgrathlexusofchicago.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.cobalt.com/cas/login" title="Cobalt Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Cobalt </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealercrm.com/" title="iMagic Control Panel" target="_new" style="color:#000000; text-decoration:none;"> iMagic </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1bl2BZYSWEL66YWRsTfa6w1Yr_lkQdFtHzA_YBUD68zs/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" border="0"> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#ffffff; background-color:#ff0000; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dFpWSmZ5V1lvZ0t6X05WcFM0aFp1U1E#gid=64" title="Mercedes Benz of Augusta - AE Portal" target="_new" style="color:#ffffff; text-decoration:none;"> MBAU </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dFpWSmZ5V1lvZ0t6X05WcFM0aFp1U1E#gid=64" title="Mercedes Benz of Augusta - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Mercedes Benz of Augusta </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.mbofaugusta.com" title="Mercedes Benz of Augusta - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.mbofaugusta.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="##" title="##" target="_new" style="color:#000000; text-decoration:none;"> - - - - </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1ucs83UE4Y8IiMYLCUxa0UDmLv5KWVvFCBc2idtpAZBo/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" border="0"> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#ffffff; background-color:#ff0000; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dFlXMjJBeUdPS2VTTjFjZDBEeFFqSUE#gid=64" title="Napleton's Des Plaines CJD - AE Portal" target="_new" style="color:#ffffff; text-decoration:none;"> NDCJ </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dFlXMjJBeUdPS2VTTjFjZDBEeFFqSUE#gid=64" title="Napleton's Des Plaines CJD - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Napleton's Des Plaines CJD </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.desplainescjd.com" title="Napleton's Des Plaines CJD - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.desplainescjd.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://www.car-research.com/carinteractive/WebXRM/loginpage.aspx" title="Car Research Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Car Research </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/10TDGVvGthdEdnMhWw456Yg4VUGOvM2fE-GmI_uYugwk/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" border="0"> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#ffffff; background-color:#ff0000; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dEI1cWZONHZCal9CRWV1MWN0clUxSXc&hl=en_US" title="Nalley Auto Group Brunswick - AE Portal" target="_new" style="color:#ffffff; text-decoration:none;"> NALY </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dEI1cWZONHZCal9CRWV1MWN0clUxSXc&hl=en_US" title="Nalley Auto Group Brunswick - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Nalley Auto Group Brunswick </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.nalley-honda.com" title="Nalley Auto Group Brunswick - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.nalley-honda.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://eleadcrm.com/evo2/fresh/login.asp" title="eLeads Control Panel" target="_new" style="color:#000000; text-decoration:none;"> eLeads </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1kmbYoHI8kkt6AesqKXs1BUyScbEa0Mf2ojx9dGEKITE/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" border="0"> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#ffffff; background-color:#ff0000; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dG1wel9pMFJEYlEwRHNwZkxLQlRPNGc#gid=64" title="Nimnicht Buick GMC - AE Portal" target="_new" style="color:#ffffff; text-decoration:none;"> NIMN </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dG1wel9pMFJEYlEwRHNwZkxLQlRPNGc#gid=64" title="Nimnicht Buick GMC - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Nimnicht Buick GMC </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.nimnichtbuickgmc.com" title="Nimnicht Buick GMC - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.nimnichtbuickgmc.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://www.gs.reyrey.com/common/login/login.aspx" title="Rey Rey Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Rey Rey </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1mb8luxeSc2vkgCPHlC8Z3GdM4nHJsICo30KU6kc0768/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" border="0"> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#ffffff; background-color:#ff0000; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center">&nbsp;</td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dG1wel9pMFJEYlEwRHNwZkxLQlRPNGc#gid=64" title="Nimnicht Chevy - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Nimnicht Chevy </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.nimnichtchevy.com" title="Nimnicht Chevy - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.nimnichtchevy.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://www.gs.reyrey.com/common/login/login.aspx" title="Rey Rey Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Rey Rey </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1mb8luxeSc2vkgCPHlC8Z3GdM4nHJsICo30KU6kc0768/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" border="0"> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#ffffff; background-color:#ff0000; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dEdDc3N0MU5mTXlqTjRHUkMyWmV2bnc#gid=64" title="Papa's CDJ - AE Portal" target="_new" style="color:#ffffff; text-decoration:none;"> PCDJ </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dEdDc3N0MU5mTXlqTjRHUkMyWmV2bnc#gid=64" title="Papa's CDJ - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Papa's CDJ </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.papasdodge.com" title="Papa's CDJ - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.papasdodge.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"> Send Blaster </td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/17gBwhFnozFBJzVHN8Ag_jswEfKlMu0jUv64Z2wE2ZDE/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" border="0"> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#ffffff; background-color:#ff0000; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=tUFl3WI5YNUGJxIL0MiDAGQ#gid=64" title="Rick Case Georgia - AE Portal" target="_new" style="color:#ffffff; text-decoration:none;"> RCGA </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=tUFl3WI5YNUGJxIL0MiDAGQ#gid=64" title="Rick Case Georgia (Deluth) - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Rick Case Georgia (Deluth) </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.rickcase.com/duluth-hyundai" title="Rick Case Georgia (Deluth) - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.rickcase.com/duluth-hyundai </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.rickcase.com/duluth-hyundai/admin" title="IZMO Cars Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Izmo Cars </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://my.dealersocket.com/crm/login.aspx" title="Dealer Socket Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer Socket </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/129oMa3IM4Iyb6Zt3IDSKVfWMOqaLL91G4uJVDmWU420/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" border="0"> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#ffffff; background-color:#ff0000; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center">&nbsp;</td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=tUFl3WI5YNUGJxIL0MiDAGQ#gid=64" title="Rick Case Georgia (Mazda) - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Rick Case Georgia (Mazda) </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.rickcase.com/mazda/" title="Rick Case Georgia (Mazda) - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.rickcase.com/mazda </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.rickcase.com/mazda/admin" title="IZMO Cars Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Izmo Cars </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://my.dealersocket.com/crm/login.aspx" title="Dealer Socket Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer Socket </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/129oMa3IM4Iyb6Zt3IDSKVfWMOqaLL91G4uJVDmWU420/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" border="0"> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#ffffff; background-color:#ff0000; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center">&nbsp;</td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=tUFl3WI5YNUGJxIL0MiDAGQ#gid=64" title="Rick Case Georgia (Roswell) - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Rick Case Georgia (Roswell) </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.rickcase.com/roswell-hyundai/" title="Rick Case Georgia (Roswell) - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.rickcase.com/roswell-hyundai/ </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.rickcase.com/roswell-hyundai/admin" title="IZMO Cars Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Izmo Cars </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://my.dealersocket.com/crm/login.aspx" title="Dealer Socket Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer Socket </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/129oMa3IM4Iyb6Zt3IDSKVfWMOqaLL91G4uJVDmWU420/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" border="0"> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#ffffff; background-color:#ff0000; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dEVHQlBsMVVXM0cwTXZGa0pBWS1CVlE" title="Spartanburg Chrysler Dodge Jeep - AE Portal" target="_new" style="color:#ffffff; text-decoration:none;"> SCDJ </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dEVHQlBsMVVXM0cwTXZGa0pBWS1CVlE" title="Spartanburg Chrysler Dodge Jeep - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Spartanburg Chrysler Dodge Jeep </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.spartanburgchryslerdodgejeep.com" title="Spartanburg Chrysler Dodge Jeep - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.spartanburgchryslerdodgejeep.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://www.gs.reyrey.com/common/login/login.aspx" title="Rey Rey Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Rey Rey </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1RUjnE6hXqmztk-71R5BnIJUEIhXJR15mWw3UAabuU8Y/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" border="0"> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#ffffff; background-color:#ff0000; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dGVpNW14ZnVzZWg0ckI5azZqa3ZDa0E#gid=64" title="Steve White Audi - AE Portal" target="_new" style="color:#ffffff; text-decoration:none;"> STVA </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dGVpNW14ZnVzZWg0ckI5azZqa3ZDa0E#gid=64" title="Steve White Audi - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Steve White Audi </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.stevewhiteaudi.com" title="Steve White Audi - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.stevewhiteaudi.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://eleadcrm.com/evo2/fresh/login.asp" title="eLeads Control Panel" target="_new" style="color:#000000; text-decoration:none;"> eLeads </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1iDR8AJOgPG5d2cCaoa-fS8Sx3qKy3DC5z1NumNmcOUI/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" border="0"> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#ffffff; background-color:#ff0000; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center">&nbsp;</td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dGVpNW14ZnVzZWg0ckI5azZqa3ZDa0E#gid=64" title="Steve White Volkswagen - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Steve White Volkswagen </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.stevewhitevw.com" title="Steve White Volkswagen - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.stevewhitevw.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://eleadcrm.com/evo2/fresh/login.asp" title="eLeads Control Panel" target="_new" style="color:#000000; text-decoration:none;"> eLeads </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1iDR8AJOgPG5d2cCaoa-fS8Sx3qKy3DC5z1NumNmcOUI/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" border="0"> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#ffffff; background-color:#ff0000; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center">&nbsp;</td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid; color:#bbbbbb;"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dGVpNW14ZnVzZWg0ckI5azZqa3ZDa0E#gid=64" title="Steve White VW - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Steve White VW (Dealer) </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid; color:#bbbbbb;"><a href="http://www.steve-white.vwdealer.com" title="Steve White VW - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.steve-white.vwdealer.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid; color:#bbbbbb;"><a href="https://login.cobalt.com/cas/login" title="Cobalt Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Cobalt </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid; color:#bbbbbb;"><a href="http://eleadcrm.com/evo2/fresh/login.asp" title="eLeads Control Panel" target="_new" style="color:#000000; text-decoration:none;"> eLeads </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1iDR8AJOgPG5d2cCaoa-fS8Sx3qKy3DC5z1NumNmcOUI/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" border="0"> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#ffffff; background-color:#ff0000; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dDlyWXNLTzFrQ0FNY1lEMUY0ekFZNVE#gid=64" title="Toyota of Rock Hill - AE Portal" target="_new" style="color:#ffffff; text-decoration:none;"> TORH </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dDlyWXNLTzFrQ0FNY1lEMUY0ekFZNVE#gid=64" title="Toyota of Rock Hill - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Toyota of Rock Hill </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.toyotarockhill.com" title="Toyota of Rock Hill - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.toyotarockhill.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="##" title="##" target="_new" style="color:#000000; text-decoration:none;"> - - - - </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1OABKbBRwunkV6um88cWeLzQ8VsSIj9iyDaTyApUIp5g/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" border="0"> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#ffffff; background-color:#ff0000; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dFBQSW84ekx4SFZsajhtUld3SlZmMWc#gid=64" title="Toyota West - AE Portal" target="_new" style="color:#ffffff; text-decoration:none;"> TOWE </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dFBQSW84ekx4SFZsajhtUld3SlZmMWc#gid=64" title="Toyota West - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Toyota West </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://toyotawest.com" title="Toyota West - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://toyotawest.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://login.nakedlime.com/Login/Login.aspx?ReturnUrl=%2fDefault.aspx" title="Naked Lime Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Naked Lime </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="##" title="##" target="_new" style="color:#000000; text-decoration:none;"> CRM </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1IDoDgwHfyHEr7buu_6gief1gZOnB_mkatUU47PSk7FY/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" border="0"> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#ffffff; background-color:#ff0000; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dHNVZHFhbU04bjBDNnBTVDNSaE5xOHc#gid=64" title="World Ford Stone Mountain - AE Portal" target="_new" style="color:#ffffff; text-decoration:none;"> WFSM </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dHNVZHFhbU04bjBDNnBTVDNSaE5xOHc#gid=64" title="World Ford Stone Mountain - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> World Ford Stone Mountain </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.worldfordstonemountain.com" title="World Ford Stone Mountain - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.worldfordstonemountain.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="##" title="##" target="_new" style="color:#000000; text-decoration:none;"> - - - - </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1oA1aj5eYDahTSDDKRhDrl96U50hFK8ur4DUktQTyQ0o/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" border="0"> </a></td>
      </tr>
    </table>
    <div class="clear"></div>
  </div>
</div>
