<div class="wrapper content-padding">
  <div id="master_list" class="content-page">
    <h2>Green Team Directory</h2>
    <h3>Adam, Jesse Michelle</h3>
    <table width="1000" cellpadding="8" cellspacing="0" style="font-size:14px; font-family:Arial, Helvetica, sans-serif;">
      <tr style="font-weight:bold; height:35px;">
        <td width="60" style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; background-color:#000000; color:#ffffff;"> Code </td>
        <td width="250" style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; background-color:#000000; color:#ffffff;"> Dealership </td>
        <td width="310" style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; background-color:#000000; color:#ffffff;"> Website </td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; background-color:#000000; color:#ffffff;"> CMS </td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; background-color:#000000; color:#ffffff;"> CRM </td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; background-color:#000000; color:#ffffff;"> DOC </td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#000000; background-color:#01cb30; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=tiyiMWB4YUieuLMp-bd-oOQ#gid=64" title="Berglund of Bedford - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> BRBF </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=tiyiMWB4YUieuLMp-bd-oOQ#gid=64" title="Berglund of Bedford - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Berglund of Bedford </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.berglundofbedford.com" title="Berglund of Bedford - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.berglundofbedford.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealercrm.com/" title="iMagic Control Panel" target="_new" style="color:#000000; text-decoration:none;"> iMagic </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1EJg5YPtqpRKw8vXU3cDXjPiRZTd3WzU_rGmkP2XceVU/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" /> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#000000; background-color:#01cb30; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=tiyiMWB4YUieuLMp-bd-oOQ#gid=64" title="Berglund of Bedford Ford - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> BRBF </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=tiyiMWB4YUieuLMp-bd-oOQ#gid=64" title="Berglund of Bedford Ford - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Berglund of Bedford Ford </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.berglundofbedfordford.com" title="Berglund of Bedford Ford - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.berglundofbedfordford.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealercrm.com/" title="iMagic Control Panel" target="_new" style="color:#000000; text-decoration:none;"> iMagic </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1EJg5YPtqpRKw8vXU3cDXjPiRZTd3WzU_rGmkP2XceVU/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" /> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#000000; background-color:#01cb30; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=tylkXi-Su05nD_oT_mohyWw#gid=64" title="Berglund Chevrolet - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> BRCH </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=tylkXi-Su05nD_oT_mohyWw#gid=64" title="Berglund Chevrolet - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Berglund Chevrolet </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.berglundchevy.com" title="Berglund Chevrolet - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.berglundchevy.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealercrm.com/" title="iMagic Control Panel" target="_new" style="color:#000000; text-decoration:none;"> iMagic </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1hs4j3bxkmF63104EdN8l2d8kTFODvwZYH67Y7mXu8Ts/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" /> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#000000; background-color:#01cb30; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=tFD0XV6brROnXza_DNzi10Q#gid=64" title="Berglund Chrysler Jeep - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> BRCJ </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=tFD0XV6brROnXza_DNzi10Q#gid=64" title="Berglund Chrysler Jeep - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Berglund Chrysler Jeep </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.berglundchryslerjeep.net" title="Berglund Chrysler Jeep - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.berglundchryslerjeep.net </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealercrm.com/" title="iMagic Control Panel" target="_new" style="color:#000000; text-decoration:none;"> iMagic </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1dFULo-nR9uaf6cBGCfewgrqcaExkzy9yrnVRcYECGBc/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" /> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#000000; background-color:#01cb30; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=t5mLj76NEFCXDTuGYEdJjzA#gid=64" title="Berglund Fiat  - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> BRFO </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=t5mLj76NEFCXDTuGYEdJjzA#gid=64" title="Berglund Fiat  - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Berglund Fiat </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.fiatusaofroanoke.com" title="Berglund Fiat  - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.fiatusaofroanoke.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealercrm.com/" title="iMagic Control Panel" target="_new" style="color:#000000; text-decoration:none;"> iMagic </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1M8a7zA_YQrsSbAqfuXjO1WmUTQSxBVY6J9jWsd9vyqU/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" /> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#000000; background-color:#01cb30; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=t5mLj76NEFCXDTuGYEdJjzA#gid=64" title="Berglund Ford  - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> BRFO </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=t5mLj76NEFCXDTuGYEdJjzA#gid=64" title="Berglund Ford  - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Berglund Ford </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.berglundford.com" title="Berglund Ford  - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.berglundford.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealercrm.com/" title="iMagic Control Panel" target="_new" style="color:#000000; text-decoration:none;"> iMagic </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1M8a7zA_YQrsSbAqfuXjO1WmUTQSxBVY6J9jWsd9vyqU/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" /> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#000000; background-color:#01cb30; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=tryr1558sRMJOSWHd1dk5lQ#gid=64" title="Berglund Mazda - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> BRMA </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=tryr1558sRMJOSWHd1dk5lQ#gid=64" title="Berglund Mazda - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Berglund Mazda </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.berglundmazdasalem.com" title="Berglund Mazda - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.berglundmazdasalem.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealercrm.com/" title="iMagic Control Panel" target="_new" style="color:#000000; text-decoration:none;"> iMagic </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1U8z8UYqQQBpob0gcdLtEXeM5Fm-8N_LLAnX0NOFVaHU/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" /> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#000000; background-color:#01cb30; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=tY3gdPN2l1X2GQEUTAJ9lhw#gid=64" title="Berglund SUV and Imports - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> BRSI </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=tY3gdPN2l1X2GQEUTAJ9lhw#gid=64" title="Berglund SUV and Imports - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Berglund SUV and Imports </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.fiatusaofroanoke.com" title="Berglund SUV and Imports - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.fiatusaofroanoke.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealercrm.com/" title="iMagic Control Panel" target="_new" style="color:#000000; text-decoration:none;"> iMagic </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1pfnQstHjwglW5QrXi4jeCueMY78S-hLcWHqBj4Qb-wQ/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" /> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#000000; background-color:#01cb30; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=ti_AwgkdQMjs9hll5-cONXg#gid=64" title="Berglund Toyota - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> BRTO </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=ti_AwgkdQMjs9hll5-cONXg#gid=64" title="Berglund Toyota - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Berglund Toyota </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.berglundtoyota.com" title="Berglund Toyota - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.berglundtoyota.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealercrm.com/" title="iMagic Control Panel" target="_new" style="color:#000000; text-decoration:none;"> iMagic </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1YuXMDP64rmSF1rg3xQWuf9CGblt6tZYkRfTHUxuS9UM/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" /> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#000000; background-color:#01cb30; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=tWgkSsXP7CzUBGaVTh3ZjzQ#gid=64" title="Bill Currie Ford Lincoln - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> BCFO </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=tWgkSsXP7CzUBGaVTh3ZjzQ#gid=64" title="Bill Currie Ford Lincoln - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Bill Currie Ford Lincoln </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.billcurrie.com" title="Bill Currie Ford Lincoln - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.billcurrie.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://www.car-research.com/carinteractive/WebXRM/loginpage.aspx" title="Car Research Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Car Research </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1pneR-bnPBFKHwFONHg5vqGhGEok68oZXpDYpdxYlSFA/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" /> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#000000; background-color:#01cb30; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=tSkiuj7O2eMKeA958YplX7Q#gid=64" title="Farrell Chevrolet - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> FACH </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=tSkiuj7O2eMKeA958YplX7Q#gid=64" title="Farrell Chevrolet - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Farrell Chevrolet </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.farrellchevrolet.com" title="Farrell Chevrolet - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.farrellchevrolet.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealercrm.com/" title="iMagic Control Panel" target="_new" style="color:#000000; text-decoration:none;"> iMagic </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1yYnknmLUe92sOKI1ekHFdIAUxPtbxlydITfUxe_vJag/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" /> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#000000; background-color:#01cb30; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=t5aunZTHE2vxmtFZrPrxzBg#gid=64" title="Farrell Kia - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> FAKI </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=t5aunZTHE2vxmtFZrPrxzBg#gid=64" title="Farrell Kia - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Farrell Kia </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.farrellkia.com" title="Farrell Kia - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.farrellkia.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealercrm.com/" title="iMagic Control Panel" target="_new" style="color:#000000; text-decoration:none;"> iMagic </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/12kPatygbY5MOGDUEtATaQrRIjqVkasO7Ks0AxvgSGw8/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" /> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#000000; background-color:#01cb30; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=tCGGDnXxLtPJbh4T0cAqCKA#gid=64" title="Harry's on the Hill - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> HAHI </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=tCGGDnXxLtPJbh4T0cAqCKA#gid=64" title="Harry's on the Hill - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Harry's on the Hill (Dealer) </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.harrysonthehill.com" title="Harry's on the Hill (Dealer) - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.harrysonthehill.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1cPPEV-hoMxbqPpcyQyD-96nrMkZY-9zwPKxEQGiAvck/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" /> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#000000; background-color:#01cb30; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=tCGGDnXxLtPJbh4T0cAqCKA#gid=64" title="Harry's on the Hill - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> HAHI </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=tCGGDnXxLtPJbh4T0cAqCKA#gid=64" title="Harry's on the Hill - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Harry's on the Hill (Cobalt) </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.harrysofasheville.com" title="Harry's on the Hill (Cobalt) - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.harrysofasheville.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.cobalt.com/cas/login" title="Cobalt Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Cobalt </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1cPPEV-hoMxbqPpcyQyD-96nrMkZY-9zwPKxEQGiAvck/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" /> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#000000; background-color:#01cb30; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=0Ag35Ehid_faMdEpwd29ON0R0UHExaDVZT1hlZWttd2c&hl=en&ndplr=1#gid=64" title="Honda of Morristown - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> MSHO </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=0Ag35Ehid_faMdEpwd29ON0R0UHExaDVZT1hlZWttd2c&hl=en&ndplr=1#gid=64" title="Honda of Morristown - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Honda of Morristown </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.hondamorristown.com" title="Honda of Morristown - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.hondamorristown.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.dealeron.com/manage-it/" title="Dealer On Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer On </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://eleadcrm.com/evo2/fresh/login.asp" title="eLeads Control Panel" target="_new" style="color:#000000; text-decoration:none;"> eLeads </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1WU4AS2wdnJbGLZXN881P8S8b3yQnAPifpK4acJ1F0hs/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" /> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#000000; background-color:#01cb30; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=t8l82wBTyLKZIFPJKO3NGJw#gid=64" title="Jeremy Franklin Suzuki - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> JFSZ </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=t8l82wBTyLKZIFPJKO3NGJw#gid=64" title="Jeremy Franklin Suzuki - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Jeremy Franklin Suzuki </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.jeremyfranklin.com" title="Jeremy Franklin Suzuki - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.jeremyfranklin.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.e-autobusiness.com/" title="Aeros Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Aero's </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1Z71j7NdJFcftSVKyEOeSWNg_nb4ww4i-oPsKtwJJPPY/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" /> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#000000; background-color:#01cb30; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dHY3cE9OQk9MUGVlVDkxa3lzTmxZanc#gid=64" title="Joe Johnson Chevrolet - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> JJCH </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dHY3cE9OQk9MUGVlVDkxa3lzTmxZanc#gid=64" title="Joe Johnson Chevrolet - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Joe Johnson Chevrolet </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.joejohnsonchevrolet.com" title="Joe Johnson Chevrolet - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.joejohnsonchevrolet.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"> Auto Accelerator </td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/10LQhT5Mj9Y9u_JtneofA3_auETZeMIxb3DpyHbgNRbM/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" /> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#000000; background-color:#01cb30; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=tC-2a9QyHZDKJ6OKkvQ3YfA#gid=64" title="Kia of Lynchburg - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> KILY </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=tC-2a9QyHZDKJ6OKkvQ3YfA#gid=64" title="Kia of Lynchburg - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Kia of Lynchburg </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.kiaoflynchburg.com" title="Kia of Lynchburg - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.kiaoflynchburg.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1g2xCQV68WWwvkhKa_3pSXu_P8Y0drHiV2iEfD5V_45A/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" /> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#000000; background-color:#01cb30; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=tR0-YqrzsFxwMdr8IKTgO_w#gid=64" title="Midpoint Chevrolet - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> MDCH </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=tR0-YqrzsFxwMdr8IKTgO_w#gid=64" title="Midpoint Chevrolet - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Midpoint Chevrolet </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.midpointchevy.com" title="Midpoint Chevrolet - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.midpointchevy.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealercrm.com/" title="iMagic Control Panel" target="_new" style="color:#000000; text-decoration:none;"> iMagic </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1l69xMmqNVMWvkpCHC08DhEdJQhhAEZuaJTvhM3XBzOo/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" /> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#000000; background-color:#01cb30; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=tk8zWjYA-EDh1Cd-E-Ti4nQ#gid=64" title="Morganton Honda - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> MOHO </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://spreadsheets.google.com/a/dealeronlinemarketing.com/ccc?key=tk8zWjYA-EDh1Cd-E-Ti4nQ#gid=64" title="Morganton Honda - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Morganton Honda </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.morgantonhonda.com" title="Morganton Honda - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.morgantonhonda.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://www.gs.reyrey.com/common/login/login.aspx" title="Rey Rey Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Rey Rey </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/10xB3P3Z9hui3DjXvup0hF0dLhs8D-Sb-lPpfWkydq60/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" /> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#000000; background-color:#01cb30; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dDdVQ29zSGFtUmFaXzF6aUdvVzQ1Nmc#gid=64" title="Phil Bachman Honda - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> PBHO </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dDdVQ29zSGFtUmFaXzF6aUdvVzQ1Nmc#gid=64" title="Phil Bachman Honda - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Phil Bachman Honda </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.pbhonda.com" title="Phil Bachman Honda - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.pbhonda.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.dealeron.com/manage-it/" title="Dealer On Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer On </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://eleadcrm.com/evo2/fresh/login.asp" title="eLeads Control Panel" target="_new" style="color:#000000; text-decoration:none;"> eLeads </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1EyR-bQ5R-TYt9QCPO0TS32vfPdTPe-pg8AABq4YdIe8/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" /> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#000000; background-color:#01cb30; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dGhtX1Ntd3o0d0JIQmdVa3REcnVIRkE#gid=64" title="Phil Bachman Toyota Scion - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> PBTO </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dGhtX1Ntd3o0d0JIQmdVa3REcnVIRkE#gid=64" title="Phil Bachman Toyota Scion - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Phil Bachman Toyota Scion </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.pbtoyota.com" title="Phil Bachman Toyota Scion - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.pbtoyota.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.dealeron.com/manage-it/" title="Dealer On Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer On </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://eleadcrm.com/evo2/fresh/login.asp" title="eLeads Control Panel" target="_new" style="color:#000000; text-decoration:none;"> eLeads </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1V61WPflWeoH4SNwxaEXBKSiAqB5maJmgyKiq7Y2njPU/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" /> </a></td>
      </tr>
      <tr height="30">
        <td width="60" style="color:#000000; background-color:#01cb30; font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dEt3Mno2UzFPZWs5S0NabTM0NWFqR0E&hl=en_US#gid=64" title="Strosnider Chevrolet - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> STCH </a></td>
        <td style="font-weight:bold; border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://docs.google.com/a/dealeronlinemarketing.com/spreadsheet/ccc?key=0AiDINbcjWPg5dEt3Mno2UzFPZWs5S0NabTM0NWFqR0E&hl=en_US#gid=64" title="Strosnider Chevrolet - AE Portal" target="_new" style="color:#000000; text-decoration:none;"> Strosnider Chevrolet </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://www.strosniderchevrolet.com" title="Strosnider Chevrolet - Main Website" target="_new" style="color:#000000; text-decoration:none;"> http://www.strosniderchevrolet.com </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="https://login.dealer.com/login?service=https%3A%2F%2Fapps.dealer.com%2Fwelcome%2Fj_spring_cas_security_check%3Bjsessionid%3D0B9594F00ED0BF961C09C298E7EB7991.wcccwelcome2-welcome_p9440" title="Dealer.com Control Panel" target="_new" style="color:#000000; text-decoration:none;"> Dealer </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; padding-left:10px; border-right:thin; border-right-color:#666666; border-right-style:solid;"><a href="http://eleadcrm.com/evo2/fresh/login.asp" title="eLeads Control Panel" target="_new" style="color:#000000; text-decoration:none;"> eLeads </a></td>
        <td style="border-bottom:thin; border-bottom-color:#666666; border-bottom-style:solid; border-right:thin; border-right-color:#666666; border-right-style:solid;" align="center"><a href="https://docs.google.com/a/dealeronlinemarketing.com/document/d/1iE36EFGV1ZrZoFvevnEg0eHUvvb0_APCkvD2mNnA-aA/edit" title="Go To Copy Doc" target="_new" style="color:#000000; text-decoration:none;"> <img src="<?= base_url() . 'Assets/' . THEMEDIR . 'imgs/doc.png'; ?>" alt="Go To Copy Doc" style="padding-left:5px; padding-right:5px;" /> </a></td>
      </tr>
    </table>
    <div class="clear"></div>
  </div>
</div>
