$(function(){
	$('#loginForm_Area').html('<div id="loginForm_Box"><form action="javascript:checkPassword();" method="post"><div id="loginForm_Fields"><label>Email</label><input name="loginForm_Username" id="loginForm_Username" type="text" /><label>Password</label><input name="loginForm_Password" id="loginForm_Password" type="password" /><br/><br/><label id="loginForm_Failure" style="font-weight: bold; color: rgb(255, 0, 0);">Incorrect username/password</label><br></div><div id="loginForm_Footer"><div id="loginForm_Forgot"><a href="javascript:forgotPassword();">Forgot My Password</a></div><div id="loginForm_Submit"><input value="Login" type="submit" /></div></div></form></div>');
	$('#loginForm_Area').append('<!-- lost Password --><div id="passwordForm_Box"><form action="javascript:lostPassword();" method="post" name="lost"><label>Email Address</label><br/><input name="email" id="passwordForm_Username" type="text" /><br/><br/><br/><div id="loginForm_Btn"><input value="Reset" type="submit" id="passwordForm_Btn" /></div><div id="back2_Login"><a href="javascript:showLogin();">Back to Login</a></div></form><div id="loginFail" style="font-weight:bold; color:#FF0000;"><br />You have failed to log in 5 times. Please reset your password.</div><div id="userFail" style="font-weight:bold; color:#FF0000;">There is no account associated with this email address.</div><div id="emailFail" style="font-weight: bold; color: rgb(255, 0, 0);">Please enter a valid email address</div></div>');
	$('#loginForm_Area').append('<!-- Password reset notification --><div id="passwordReset_Box"><div id="password_reset"><span>Your password is being reset and will be emailed to you shortly. Click the link below to return to the login page.</span><br/><div id="return"><a href="javascript:showLogin();">Return Home</a></div></div></div>');
	$('#loginForm_Area').append('<!-- change new password --><div id="newPassword_Box"><form action="javascript:submitPassword();" method="post" name="Reset"><label>New Password:</label><br/><input name="newPassword_Field1" id="newPassword_Field1" type="password" /><br/><label><strong>Confirm New Password:</strong></label><br/><input name="newPassword_Field2" id="newPassword_Field2" type="password" /><br/><br/><input value="Update Password" type="submit" id="newPassword_Btn" /></form><div id="newPassword_Invalid" style="font-weight:bold; color:#FF0000; ">Passwords do not match. Please enter the same password in both fields.</div><div id="newPassword_Fail" style="font-weight:bold; color:#FF0000; ">Something went wrong. Our trained code monkeys are attempting to fix the problem.</div></div>');
	$('#loginForm_Area').append('<!-- spinner --><div style="" id="loginSpinner_Wrapper"><div id="loginSpinner_Img"><img src="img/login/spinner.gif" width="60"></div></div>');
	$('#passwordForm_Box').hide();
	$('#loginFail').hide();
	$('#userFail').hide();
	$('#emailFail').hide();
	$('#passwordReset_Box').hide();
	$('#loginSpinner_Wrapper').hide();
	$('#newPassword_Box').hide();
	$('#loginForm_Failure').hide();
	$('#loginForm_Username').focus();
});